// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCqLLQtKn545KWA_xbJuhm2ZUQnxlkRSY',
    appId: '1:1091612498519:android:2b076bf52258eba4112112',
    messagingSenderId: '1091612498519',
    projectId: 'el-tracker-8dcc8',
    storageBucket: 'el-tracker-8dcc8.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWvrAJYs5FfCDsWJHhObbMi2RJvVzMRnI',
    appId: '1:1091612498519:web:36db80c1d2babac5112112',
    messagingSenderId: '1091612498519',
    projectId: 'el-tracker-8dcc8',
    authDomain: 'el-tracker-8dcc8.firebaseapp.com',
    storageBucket: 'el-tracker-8dcc8.firebasestorage.app',
    measurementId: 'G-838YVDC3PX',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3LiYZCw8RsHM07fX-NeBGV0kI9uzZlHY',
    appId: '1:1091612498519:ios:11d818940d9c2fca112112',
    messagingSenderId: '1091612498519',
    projectId: 'el-tracker-8dcc8',
    storageBucket: 'el-tracker-8dcc8.firebasestorage.app',
    iosBundleId: 'com.example.eltrackerApp',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3LiYZCw8RsHM07fX-NeBGV0kI9uzZlHY',
    appId: '1:1091612498519:ios:11d818940d9c2fca112112',
    messagingSenderId: '1091612498519',
    projectId: 'el-tracker-8dcc8',
    storageBucket: 'el-tracker-8dcc8.firebasestorage.app',
    iosBundleId: 'com.example.eltrackerApp',
  );

}